name: Lint and Test

on:
  push:
    branches: [ main ]
    tags: '**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13", "3.14", "3.14t"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - name: "Setup uv ${{ matrix.python-version }} / ${{ matrix.os }}"
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build
      run: uv sync --dev --all-extras
    - name: Lint
      run: |
        uv run ruff check
        uv run mypy .
    - name: Test
      run: |
        uv run pytest -sv
